version: "3.3"
services:
    blazegraph-docker:
        image: openkbs/blazegraph-docker
        container_name: blazegraph-docker
        ports:
            - 9999:9999
        volumes:
            ## Blazegraph data store
            - /home/swordsouler/data:/var/lib/blazegraph/data:rw
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9999", "||", "exit 1"]
            interval: 10s
            timeout: 10s
            retries: 3
        deploy:
            restart_policy:
                condition: on-failure
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: bot
